2-floating-precision: 2-floating-precision.c
	$(CC) 2-floating-precision.c -o 2-floating-precision

2-special-numbers: 2-special-numbers.c
	$(CC) 2-special-numbers.c -o 2-special-numbers

all: 2-floating-precision 2-special-numbers

clean:
	rm 2-floating-precision 2-special-numbers
